### ISSUE TITLE
More details in README.md

### ISSUE THREAD

**Issue by AslanDevbrat** [jayasridharmireddi/Data-science-task-1--GRIP-JULY2021-Internship#1]
Add more details in README.md file like, what was the aim for this project ? how you have achieved that aim ? how other people can reproduce your work?

A good looking readme file attract more people. BTW nice project  on linear regression. Hope to see more advanced project in the future

**Comment by jayasridharmireddi** [comment]
Sure, I will add details to the readme file. 
Thank you so much for the suggestions 😊😊!!
